correção cronograma
Interacao-Humano-Computador/2024.2-Grupo08 pull request #23
Opened 2024-11-11 22:54 UTC by DeM4rcio

# Checklist para Revisão de PR - Documentação de IHC

### 1. **Clareza e Objetividade**
- [ ] O conteúdo está escrito de forma clara e simples?
- [ ] Conceitos são explicados de forma acessível?
- [ ] A terminologia é consistente?

### 2. **Estrutura e Organização**
- [ ] A documentação segue uma estrutura lógica?
- [ ] Cabeçalhos estão corretamente organizados?
- [ ] Existem sumários ou links internos de navegação?
- [ ] Links ou hyperlinks funcionando corretamente?

### 3. **Consistência**
- [ ] Terminologia e formatação são consistentes?
- [ ] Exemplos seguem o mesmo padrão de apresentação?

### 4. **Exemplos**
- [ ] Existem exemplos práticos suficientes?
- [ ] Exemplos são bem explicados e relevantes?

### 5. **Atualização e Relevância**
- [ ] O conteúdo está atualizado com as últimas tendências de IHC?
- [ ] Links para materiais adicionais estão disponíveis?
- [ ] Referências estão devidamente aplicadas?

### 6. **Feedback Visual (caso haja)**
- [ ] Imagens ou diagramas são de boa qualidade e ajudam na explicação?
- [ ] As capturas de tela estão claras e bem posicionadas?

### 7. **Revisão**
- [ ] Não há erros de digitação ou gramática?
- [ ] O formato do texto está consistente e organizado?
- [ ] Foi inserido o histórico de verão?

2024-11-11 23:08 UTC, kaioenzo requested changes

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Processo de Design|Início: 02/11 <br>Fim: 07/11|kaio|Início:08/11 <br>Fim:09/11|Luiza|
```suggestion
|Processo de Design|Início: 02/11 <br>Fim: 07/11| Kaio |Início:08/11 <br>Fim:09/11|Luiza|
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Gravar apresentação|Início:11/11 <br>Fim:11/11|Todos|Início:12/11 <br>Fim:12/11|kaio|
```suggestion
|Gravar apresentação|Início:11/11 <br>Fim:11/11|Todos|Início:12/11 <br>Fim:12/11| Kaio |
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Correção após apresentação| Início:12/11 <br>Fim:12/11 |Márcio|Início:12/11 <br>Fim:12/11|kaio|
```suggestion
|Correção após apresentação| Início:12/11 <br>Fim:12/11 |Márcio|Início:12/11 <br>Fim:12/11| Kaio |
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Sites Avaliados|Início: 06/11 <br>Fim: 06/11|Márcio|Início:11/11 <br>Fim:11/11|kaio|
```suggestion
|Sites Avaliados|Início: 06/11 <br>Fim: 06/11|Márcio|Início:11/11 <br>Fim:11/11| Kaio |
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Gravar apresentação|Início:12/11 <br>Fim:12/11|Todos|Início:12/11 <br>Fim:12/11|kaio|
```suggestion
|Gravar apresentação|Início:12/11 <br>Fim:12/11|Todos|Início:12/11 <br>Fim:12/11| Kaio |
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +|Correção após apresentação| Início:13/11 <br>Fim:13/11 |Márcio|Início:13/11 <br>Fim:13/11|kaio|
```suggestion
|Correção após apresentação| Início:13/11 <br>Fim:13/11 |Márcio|Início:13/11 <br>Fim:13/11| Kaio |
```

2024-11-11 23:08 UTC, kaioenzo commented on docs/planejamento/cronograma.md
> +**tabela 1** - planejamento da entrega 1
```suggestion
**tabela 1** - Planejamento da entrega 1
```

2024-11-12 00:56 UTC, LuizaMaluf reviewed
LGTM

2024-11-12 00:57 UTC, merged